name: Capture Changed Files on Merge

on:
  pull_request:
    types: [closed]
    branches:
      - "projectA"
      - "project/qa"
      - "project/prod"
      - "master"

jobs:
  file-list:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        run: |
          echo "Changed files:" > changed-files.txt
          git diff --name-only \
            ${{ github.event.pull_request.base.sha }} \
            ${{ github.event.pull_request.head.sha }} >> changed-files.txt

      - name: Upload file list
        uses: actions/upload-artifact@v4
        with:
          name: changed-files-${{ github.event.pull_request.number }}
          path: changed-files.txt

